In [19]:
import numpy as np

In [98]:
X = np.array([[1,2],[3,4],[5,6],[7,8]])
y = np.array([[3],[5],[6],[7]])
m, dim = X.shape
theta = np.array([[2],[3]])

In [99]:
np.square(theta).sum(axis = 0)

array([13])

In [100]:
h = 1 - np.matmul(X,theta)
h.shape

(4, 1)

In [101]:
z = np.zeros(m).reshape(-1,1)

In [102]:
check = (h > 0).astype(float)
check

array([[0.],
       [0.],
       [0.],
       [0.]])

In [103]:
np.matmul(X.T,y)

array([[ 97],
       [118]])

In [123]:
x1 = np.array([1,2,3])
x2 = np.array([2,3,4])
np.sqrt(np.square(x1 - x2).sum())

1.7320508075688772

In [124]:
theta = np.array([[1,2,3,4],[4,5,4,5],[6,7,8,9]])

In [125]:
theta[:,1]

array([2, 5, 7])

In [126]:
theta[1,:]

array([4, 5, 4, 5])

In [143]:
theta = []
y = np.array([[0],[2],[1],[0]])
Np = np.zeros((4,3))
for i in range(len(y)):
    Np[i,y[i]] = 1
Np

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [144]:
a = np.array([[1,2,3],[2,3,4],[5,5,5]])
b = np.array([[1],[1],[1]])

In [145]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [5, 5, 5]])

In [146]:
b

array([[1],
       [1],
       [1]])

In [147]:
a-b

array([[0, 1, 2],
       [1, 2, 3],
       [4, 4, 4]])