In [19]:
import numpy as np

In [98]:
X = np.array([[1,2],[3,4],[5,6],[7,8]])
y = np.array([[3],[5],[6],[7]])
m, dim = X.shape
theta = np.array([[2],[3]])

In [99]:
np.square(theta).sum(axis = 0)

array([13])

In [100]:
h = 1 - np.matmul(X,theta)
h.shape

(4, 1)

In [101]:
z = np.zeros(m).reshape(-1,1)

In [102]:
check = (h > 0).astype(float)
check

array([[0.],
       [0.],
       [0.],
       [0.]])

In [103]:
np.matmul(X.T,y)

array([[ 97],
       [118]])

In [123]:
x1 = np.array([1,2,3])
x2 = np.array([2,3,4])
np.sqrt(np.square(x1 - x2).sum())

1.7320508075688772

In [120]:
from scipy import spatial

In [121]:
spatial.distance.cdist(x1,x2,"euclidean")

ValueError: XA must be a 2-dimensional array.

In [ ]:
 cdist(X,np.vstack((xx.ravel(), yy.ravel())).T,'euclidean').T