In [116]:
import numpy as np

In [117]:
X = np.array([[1,0,3],[1,1,3],[1,0,1],[1,1,1]])
theta = np.array([[0],[-2],[-1]])
y = np.array([[1],[1],[0],[0]]) 

In [118]:
def sigmoid (z):
    #sig = np.zeros(z.shape)
    # Your code here
    z = np.array(z)
    sig = 1/ (1+ np.exp(-z))
    # End your code
    return sig

In [119]:
def grad_loss(theta,X,y,reg):
    m,dim = X.shape
    grad = np.zeros((dim,))
    penal_arr = np.vstack([[0],theta[1:]])
    grad = 1/m * np.matmul(X.T,sigmoid(np.matmul(X,theta))-y) + reg/m*penal_arr
    return grad

In [120]:
def Hessian (theta,X,y,reg):
    m,dim = X.shape
    diag_num = sigmoid(np.matmul(X,theta))*(1-sigmoid(np.matmul(X,theta)))
    S = np.diag(list(diag_num.reshape(-1)))
    penal = reg * np.diag([1]*theta.shape[0])
    H = 1/m * (np.matmul(np.matmul(X.T,S),X) + penal)
    return H

In [121]:
g = grad_loss(theta,X,y,reg = 0.07)
H = Hessian(theta,X,y,reg = 0.07)

In [122]:
theta_first = np.matmul(np.linalg.inv(H),g)
theta_first

array([[  8.38391811],
       [ -6.64908428],
       [-10.90822476]])

In [123]:
np.linalg.inv(H)

array([[ 25.34037261,  -4.04610701, -12.59722563],
       [ -4.04610701,  35.01757033,  -0.86481126],
       [-12.59722563,  -0.86481126,  11.6430186 ]])

In [124]:
theta = theta_first
g = grad_loss(theta,X,y,reg = 0.07)
H = Hessian(theta,X,y,reg = 0.07)
theta_second = np.matmul(np.linalg.inv(H),g)
theta_second

array([[ 13.28165708],
       [-20.84094298],
       [-54.76942471]])

In [127]:
for i in range (10):
    g = grad_loss(theta,X,y,reg = 1)
    H = Hessian(theta,X,y,reg = 1)
    theta = np.matmul(np.linalg.inv(H),g)
    print ("current_iteration: %d" %i, "theta = ", theta)

current_iteration: 0 theta =  [[   -2.        ]
 [ -250.41237155]
 [-1432.19799613]]
current_iteration: 1 theta =  [[   -2.        ]
 [ -251.41237155]
 [-1438.19799613]]
current_iteration: 2 theta =  [[   -2.        ]
 [ -252.41237155]
 [-1444.19799613]]
current_iteration: 3 theta =  [[   -2.        ]
 [ -253.41237155]
 [-1450.19799613]]
current_iteration: 4 theta =  [[   -2.        ]
 [ -254.41237155]
 [-1456.19799613]]
current_iteration: 5 theta =  [[   -2.        ]
 [ -255.41237155]
 [-1462.19799613]]
current_iteration: 6 theta =  [[   -2.        ]
 [ -256.41237155]
 [-1468.19799613]]
current_iteration: 7 theta =  [[   -2.        ]
 [ -257.41237155]
 [-1474.19799613]]
current_iteration: 8 theta =  [[   -2.        ]
 [ -258.41237155]
 [-1480.19799613]]
current_iteration: 9 theta =  [[   -2.        ]
 [ -259.41237155]
 [-1486.19799613]]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """
