In [2]:
import numpy as np

In [4]:
def htheta_matrix(theta,X):
    # the sigmoid function
    return 1/(1+np.exp(-1*np.dot(X,theta)))


def de_loss(X,y,theta,lam):
    m=X.shape[0]
    return  -1/m *np.dot(X.T,(y-htheta_matrix(theta,X))) +lam/m*np.hstack((0,theta[1:])) # the first is not penalized


def hessian(X,theta,lam):
    m=X.shape[0]
    n=X.shape[1]
    h_x=htheta_matrix(theta,X)
    S=np.diag(np.multiply(h_x,(1-h_x)))
    I=np.diag(np.hstack((0,np.ones(n-1)))) # need to double check
    return 1/m*(X.T.dot(np.dot(S,X))+lam*I)

X = [[1,0,3], [1,1,3], [1,1,0],[1,1,1]]
X = np.asarray(X)
y = np.array([1,1,0,0])

print(X.shape)
print(y.shape)

theta= np.array([0.0,-2.0,1.0])

lam=0.07
#print(de_loss(X,y,theta,lam))
#print(hessian(X,theta,lam))

for _ in range(200):
    theta -= np.dot(np.linalg.inv(hessian(X,theta,lam)),de_loss(X,y, theta,lam))
    print('iteration', str(_+1))
    print(theta)
    #print(de_loss(X,y,theta,lam))
    #print(hessian(X,theta,lam))

(4, 3)
(4,)
iteration 1
[-2.84688246 -0.7376565   1.91789698]
iteration 2
[-4.150125   -0.50891193  2.46217767]
iteration 3
[-4.52264212 -0.48839932  2.61960654]
iteration 4
[-4.55123757 -0.48891877  2.63040869]
iteration 5
[-4.55143391 -0.48892564  2.63047154]
iteration 6
[-4.55143392 -0.48892564  2.63047155]
iteration 7
[-4.55143392 -0.48892564  2.63047155]
iteration 8
[-4.55143392 -0.48892564  2.63047155]
iteration 9
[-4.55143392 -0.48892564  2.63047155]
iteration 10
[-4.55143392 -0.48892564  2.63047155]
iteration 11
[-4.55143392 -0.48892564  2.63047155]
iteration 12
[-4.55143392 -0.48892564  2.63047155]
iteration 13
[-4.55143392 -0.48892564  2.63047155]
iteration 14
[-4.55143392 -0.48892564  2.63047155]
iteration 15
[-4.55143392 -0.48892564  2.63047155]
iteration 16
[-4.55143392 -0.48892564  2.63047155]
iteration 17
[-4.55143392 -0.48892564  2.63047155]
iteration 18
[-4.55143392 -0.48892564  2.63047155]
iteration 19
[-4.55143392 -0.48892564  2.63047155]
iteration 20
[-4.55143392 -0

In [5]:
%run -i 'Q1.5_revised_I.py'

current_iteration: 1 theta =  [-4.67100739 -0.00823255  2.34035274]
current_iteration: 2 theta =  [-5.63804815e+00 -1.73933112e-03  2.82056371e+00]
current_iteration: 3 theta =  [-5.83542909e+00 -6.47437425e-05  2.91782611e+00]
current_iteration: 4 theta =  [-5.84222456e+00 -7.82981885e-08  2.92111258e+00]
current_iteration: 5 theta =  [-5.84223232e+00 -1.02843015e-13  2.92111616e+00]
current_iteration: 6 theta =  [-5.84223232e+00  6.30073421e-17  2.92111616e+00]
current_iteration: 7 theta =  [-5.84223232e+00  2.57898020e-17  2.92111616e+00]
current_iteration: 8 theta =  [-5.84223232e+00  1.05561331e-17  2.92111616e+00]
current_iteration: 9 theta =  [-5.84223232e+00  4.32077553e-18  2.92111616e+00]
current_iteration: 10 theta =  [-5.84223232e+00  1.76855493e-18  2.92111616e+00]
current_iteration: 11 theta =  [-5.84223232e+00  7.23894707e-19  2.92111616e+00]
current_iteration: 12 theta =  [-5.84223232e+00  2.96300408e-19  2.92111616e+00]
current_iteration: 13 theta =  [-5.84223232e+00  

In [3]:
%run -i 'Q1_5.py'

current_iteration: 1 theta =  [-3.15199171 -0.40585887  1.81504991]
current_iteration: 2 theta =  [-4.26505811 -0.29747087  2.33806757]
current_iteration: 3 theta =  [-4.90809867 -0.18354141  2.5979506 ]
current_iteration: 4 theta =  [-5.28312052 -0.10788523  2.7307514 ]
current_iteration: 5 theta =  [-5.50526622 -0.0643088   2.806734  ]
current_iteration: 6 theta =  [-5.63818741 -0.03873452  2.85196033]
current_iteration: 7 theta =  [-5.71828372 -0.02345439  2.87915056]
current_iteration: 8 theta =  [-5.76678512 -0.01424811  2.89558908]
current_iteration: 9 theta =  [-5.79624891 -0.00867314  2.90556462]
current_iteration: 10 theta =  [-5.81418413e+00 -5.28625031e-03  2.91163282e+00]
current_iteration: 11 theta =  [-5.82511557e+00 -3.22448341e-03  2.91532978e+00]
current_iteration: 12 theta =  [-5.83178346e+00 -1.96780673e-03  2.91758424e+00]
current_iteration: 13 theta =  [-5.83585268e+00 -1.20125018e-03  2.91895985e+00]
current_iteration: 14 theta =  [-5.83833673e+00 -7.33437840e-04 