In [63]:
import numpy as np

In [64]:
X = np.array([[1,2,3],[2,3,4],[3,4,5],[2,4,5]])

In [65]:
y = np.array([[1],[2],[3],[4]])

In [66]:
m, dim = X.shape

In [67]:
X, y

(array([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [2, 4, 5]]),
 array([[1],
        [2],
        [3],
        [4]]))

In [68]:
theta = np.array([[1,2],[2,3],[5,6]])
theta

array([[1, 2],
       [2, 3],
       [5, 6]])

In [69]:
panel, soft = 0, 0 
K = theta.shape[1]
# calculate the penalty term
for j in range(dim):
    for k in range(K):
        panel += theta[j][k]**2
reg = 1
panel *= reg/2/m
panel

9.875

In [70]:
y[2]

array([3])

In [72]:
for i in range(m):
    for k in range(K):
        if y[i] == k:
            top = np.exp((theta[:,k].T).dot(X[i]))
top

195729609428.83878

In [76]:
np.exp(np.matmul(X[1],theta)-max(np.matmul(X[1],theta))).sum(axis = 0)

1.0001234098040868

In [82]:
np.matmul(X[1],theta)

array([28, 37])

In [81]:
vec = np.exp(np.matmul(X[1],theta)-max(np.matmul(X[1],theta)))
vec

array([1.23409804e-04, 1.00000000e+00])

In [39]:
np.square(theta).sum(axis = 1).sum(axis = 0)

79

In [40]:
np.exp(np.matmul(X,theta))

array([[4.85165195e+08, 1.95729609e+11],
       [1.44625706e+12, 1.17191424e+16],
       [4.31123155e+15, 7.01673591e+20],
       [1.58601345e+15, 9.49611942e+19]])

In [27]:
np.matmul(X,theta).sum(axis = 1)

array([46, 65, 84, 81])

In [86]:
test = np.array([123,456,789])

In [87]:
test = test - max(test)

In [89]:
S = np.exp(test).sum(axis = 0)

1.0

In [90]:
test

array([-666, -333,    0])

In [91]:
np.exp(test)/S

array([5.75203420e-290, 2.39819191e-145, 9.99876605e-001])

In [92]:
test = np.array([123,456,789])
np.exp(test)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


array([2.61951732e+053, 1.09215367e+198,             inf])