In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,3],[2,3,4],[3,4,5],[2,4,5]])
m, dim = X.shape
X

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [2, 4, 5]])

In [56]:
y = np.array([[1],[0],[1],[0]])
y

array([[1],
       [0],
       [1],
       [0]])

In [57]:
theta = np.array([[1,2],[2,3],[5,6]])
theta

array([[1, 2],
       [2, 3],
       [5, 6]])

In [58]:
K = 2

In [59]:
panel = 0
for j in range(dim):
        for k in range(K):
            panel += theta[j,k]*theta[j,k]
panel

79

In [60]:
# Check for Panel term
panel, soft = 0, 0 
K = theta.shape[1]
# calculate the penalty term
for j in range(dim):
    for k in range(K):
        panel += theta[j][k]**2
reg = 1
panel *= reg/2/m
panel

9.875

In [61]:
p_top = np.dot(X,theta)
    # conduct transformation to avoid overflow
p_top = np.exp(p_top - np.max(p_top, axis = 1).reshape((-1,1)))
p = p_top/p_top.sum(axis = 1).reshape((-1,1))
p

array([[2.47262316e-03, 9.97527377e-01],
       [1.23394576e-04, 9.99876605e-01],
       [6.14417460e-06, 9.99993856e-01],
       [1.67014218e-05, 9.99983299e-01]])

In [62]:
s = np.exp(np.matmul(X[1],theta)-max(np.matmul(X[1],theta))).sum(axis = 0)

In [63]:
np.matmul(X[1],theta)

array([28, 37])

In [64]:
vec = np.exp(np.matmul(X[1],theta)-max(np.matmul(X[1],theta)))
vec

array([1.23409804e-04, 1.00000000e+00])

In [65]:
np.square(theta).sum(axis = 1).sum(axis = 0)

79

In [66]:
np.exp(np.matmul(X,theta))

array([[4.85165195e+08, 1.95729609e+11],
       [1.44625706e+12, 1.17191424e+16],
       [4.31123155e+15, 7.01673591e+20],
       [1.58601345e+15, 9.49611942e+19]])

In [67]:
np.matmul(X,theta).sum(axis = 1)

array([46, 65, 84, 81])

In [68]:
test = np.array([123,456,789])

In [69]:
test = test - max(test)

In [70]:
S = np.exp(test).sum(axis = 0)

In [71]:
test

array([-666, -333,    0])

In [72]:
np.exp(test)/S

array([5.75274406e-290, 2.39848787e-145, 1.00000000e+000])

In [73]:
test = np.array([123,456,789])
np.exp(test)

<ipython-input-73-faf8d4d6f053>:2: RuntimeWarning: overflow encountered in exp
  np.exp(test)


array([2.61951732e+053, 1.09215367e+198,             inf])

In [74]:
I = np.zeros((m,theta.shape[1]))
m, y.shape

(4, (4, 1))

In [75]:
I

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [76]:
for i in range(m):
    I[i,y[i]] = 1
    


In [77]:
I

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])