In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,3,4],[2,2,3,4],[3,3,0,5]])

In [4]:
np.prod(X.shape[1:])

4

In [7]:
theta0 = np.array([1,2,3,4])

In [8]:
np.expand_dims(theta0, axis=1).T

array([[1, 2, 3, 4]])

In [9]:
X

array([[1, 2, 3, 4],
       [2, 2, 3, 4],
       [3, 3, 0, 5]])

In [10]:
theta 

array([1, 2, 3, 4])

In [11]:
X + theta

array([[2, 4, 6, 8],
       [3, 4, 6, 8],
       [4, 5, 3, 9]])